### ISSUE TITLE
Game Demo(Unable to join)

### ISSUE THREAD

**Issue by ShaqAttackIsGoated** [USAR-Development/Engine-Changelog#11]
Whenever I attempt to join Game-demo, I always get a black screen. I've restarted my laptop and re-downloaded roblox. But it doesn't seem to still work. I've also noticed some other people are receiving the same issue. Here's a pic:

<img width="1440" alt="Screenshot 2023-10-11 at 7 47 52 PM" src="https://github.com/USAR-Development/Engine-Changelog/assets/147615773/65e41882-5e88-4290-8281-3d552944163c">

**Comment by Krcnos** [comment]
My account was banned so it created a start-up issue where roblox couldn't receive my account information to show in credits so the game wouldn't load
