### ISSUE TITLE
The image preview of the lockers do not appear

### ISSUE THREAD

**Issue by RavenFan9000** [USAR-Development/Engine-Changelog#12]
**Describe the bug**
Once you go to any locker all the image previews of what you can wear doesn't appear at all

**To Reproduce**
Steps to reproduce the behavior: example >>
1. Go to a locker
2. Hold E
3. The image preview of items are not there

**Expected behavior**
The images of everything I can equip to appear

**Screenshots**
![RobloxPlayerBeta_Uv8VU2cESe](https://github.com/USAR-Development/Engine-Changelog/assets/77491034/08c5e543-e3fc-45eb-8ff9-d0dc27dc82f7)
![RobloxPlayerBeta_RSdtv4P54e](https://github.com/USAR-Development/Engine-Changelog/assets/77491034/5261a244-7064-49b1-aed3-8c5c909b9b0b)
![RobloxPlayerBeta_nCbfY6VIrh](https://github.com/USAR-Development/Engine-Changelog/assets/77491034/721ebe0b-671e-4c8a-8505-7f2b55cb46e9)
![RobloxPlayerBeta_XNKPL3fFg3](https://github.com/USAR-Development/Engine-Changelog/assets/77491034/d20064cc-372d-4e45-
![RobloxPlayerBeta_rmLLrIPtRN](https://github.com/USAR-Development/Engine-Changelog/assets/77491034/173fd8dd-4965-4822-bc94
![RobloxPlayerBeta_2h9G3fmCMa](https://github.com/USAR-Development/Engine-Changelog/assets/77491034/5ac2b015-b241-4982-839d-907dec80b6d8)

![RobloxPlayerBeta_cHM7525G9q](https://github.com/USAR-Development/Engine-Changelog/assets/77491034/a44f2b03-d7cb-461b-a6fc-a549a4ef9fd5)
-19cb2cf9d2ee)
bb33-0de51cb5f737)
![RobloxPlayerBeta_PZ0LOMgsRz](https://github.com/USAR-Development/Engine-Changelog/assets/77491034/29eb3716-b8e0-4952-ae6e-fd50eece15db)

**Additional context**
N/A

**Comment by Krcnos** [comment]
fixed
