### ISSUE TITLE
Can't see icon's in the locker

### ISSUE THREAD

**Issue by sharaalt** [USAR-Development/Engine-Changelog#15]
**Describe the bug**
When you open the locker you can't see any icon's for any items in the locker.

**To Reproduce**
1. Join game
2. Open locker

**Expected behavior**
When you open the locker in-game you should see no icon's for the items in the locker for all tabs.

**Screenshots**
![image](https://github.com/USAR-Development/Engine-Changelog/assets/103602431/23cbeef2-15fd-4d53-9c90-550cbedb4917)

**Comment by RavenFan9000** [comment]
Same

**Comment by Krcnos** [comment]
fixed
