### ISSUE TITLE
Can't join fortjackson and game demo

### ISSUE THREAD

**Issue by MUSTAFE4343** [USAR-Development/Engine-Changelog#16]
Everytime i press on any button to play it takes to blackscreen.
This issue is on both games. In usar server bug reports there are many
 people with same issue.
https://cdn.discordapp.com/attachments/935561170620919818/1162671404219637840/RobloxScreenShot20231014_102529720.png?ex=653cc920&is=652a5420&hm=184727ebeffa454d369ead5d1aa7e82e075f63d8a3669a622a98c1aeccf20257&

**Comment by Krcnos** [comment]
fixed
