### ISSUE TITLE
Black screen after joining the game.

### ISSUE THREAD

**Issue by gavawapa** [USAR-Development/Engine-Changelog#18]
**Describe the bug**
After joining the game, just a black screen appears.

**To Reproduce**
Steps to reproduce the behavior: example >>
1. Join the game.
2. After clicking anywhere to start, the black screen appears.

**Expected behavior**
The game just doesn't let you to view, or do anything. As i said, you can only see a black screen.

**Screenshots**
![Screenshot 2023-10-14 122402](https://github.com/USAR-Development/Engine-Changelog/assets/147917673/46a87872-b604-45d3-a238-3dfdd55e1172)

**Additional context**
N/A.

**Comment by Krcnos** [comment]
fixed
