### ISSUE TITLE
Replace the helicopter sound with something more audibly pleasant

### ISSUE THREAD

**Issue by m-ati** [USAR-Development/Engine-Changelog#2]
**Is your feature request related to a problem? Please describe.**
The current helicopter sound is just pretty generic and worst of all you can hear the moment it loops.

**Describe the solution you'd like**
Replace the current helicopter sound. I've featured some examples that could be used below.

**Describe alternatives you've considered**
Keep the current sound but at least fix it so you can't hear when it loops.

**Additional context**
https://cdn.discordapp.com/attachments/906944381804748831/1142191326549528606/Example1.ogg
https://cdn.discordapp.com/attachments/906944381804748831/1142191297319415858/Example2.ogg
https://cdn.discordapp.com/attachments/906944381804748831/1142191244668317736/Example3.ogg

**Comment by Krcnos** [comment]
I'll probably just use those sounds lol, thanks for providing
