### ISSUE TITLE
Frozen as Recruiting & Retention College Recruiting Staff

### ISSUE THREAD

**Issue by flameyburnsy** [USAR-Development/Engine-Changelog#30]
I'm a Recruiting Instructor and when I enter locked boxes I get frozen. This is a issue that shouldn't happen so please make it so Recruiting & Retention College officials do not get frozen when entering locked boxes.

**Comment by Krcnos** [comment]
This is intentional. You should be inside of a pavilion before it locks, unless you are the owner of that pav, in MPC, or are an HQ member you cannot go in and out.
