### ISSUE TITLE
Spent 1050R$ 1 years ago and can no longer skydive since the game got renamed fort jackson

### ISSUE THREAD

**Issue by willyrire** [USAR-Development/Engine-Changelog#4]
**Describe the bug**
i CANT skydive even if i bought the skydive gamepass when the game was still called Fort Martin.

**To Reproduce**
Steps to reproduce the behavior: example >>
1. Go see xavier or the instructor
2. Ask to skydive
3. Get no answer and stay on grounnd

**Expected behavior**
GETTING BROUGHT TO THE PLANE DUH

**Comment by Krcnos** [comment]
This is a support issue not a game issue. The name change of the game did not alter any of the gamepasses in any way. If you owned it before the name change, you would continue to own it afterwards. Make sure that you are not in VIP mode to skydive.
