### ISSUE TITLE
Shirt bug

### ISSUE THREAD

**Issue by Demon24agent2** [USAR-Development/Engine-Changelog#40]
**Describe the bug**
Whenever I join the game everything is ok. But after some time the uniform start getting blurred for me and sometimes the faces as well.

**Comment by Demon24agent2** [comment]
Photo in which everything is normal. https://photos.app.goo.gl/zsy7jRXMNfRDxxhh6.             Photo in which uniforms start getting blurred.                 https://cdn.discordapp.com/attachments/1031831986668572712/1172798655074406410/Screenshot_20231111_124457_com.roblox.client.jpg?ex=6561a0dc&is=654f2bdc&hm=8eed674b88827251b78f33ffcdb08811525c0a7b6380dd3a88aa26bb758e822e& https://cdn.discordapp.com/attachments/1031831986668572712/1172798654466240662/Screenshot_20231111_124520_com.roblox.client.jpg?ex=6561a0dc&is=654f2bdc&hm=cfa0c24ab362b297a13da398152d259308404f2f8dd0446fa43da0608f9dd87c& https://cdn.discordapp.com/attachments/1031831986668572712/1172798654776627230/Screenshot_20231111_124529_com.roblox.client.jpg?ex=6561a0dc&is=654f2bdc&hm=3dcb136444ce70ccb2aa20733f790f2083cbe43c80a529ca3b82862c3c8d885b&https://cdn.discordapp.com/attachments/1031831986668572712/1172798654118105138/Screenshot_20231111_124606_com.roblox.client.jpg?ex=6561a0dc&is=654f2bdc&hm=deee4482da997d4c4574414048b61c50f2d059d44b9cee0eb42e587ae0620ed6&

**Comment by Demon24agent2** [comment]
You need to fix this ASAP. I have to rejoin again and again because of this .

**Comment by Krcnos** [comment]
This is a memory saving technique roblox uses to boost your devices performance. There is nothing I can do to alter or fix it on my end.
