### ISSUE TITLE
Almost everything of my screen turns black when I equip my gun

### ISSUE THREAD

**Issue by MrChaosNeon** [USAR-Development/Engine-Changelog#5]
**Describe the bug**
Basically when I equip my gun, all of my screen (not only in roblox) will turn black depends where my cursor is.

**To Reproduce**
1. Equip the gun
2. Half of the screen turns black when the cursor is in the middle of the display

**Expected behavior**
While you have your gun equipped, the whole screen shouldn't have a black spot...

**Video**
https://imgur.com/a/p6BpPi7

**Additional context**
Tried recording it with OBS studio so I won't have to record it with my phone, but turns out the video won't show the black spot.
Sorry if I couldn't properly describe the bug.

**Comment by Krcnos** [comment]
That's an isolated issue on your actual computer, maybe when you hit the number keys on the top of your keyboard. It's covering your windows taskbar at the bottom of your screen which means it doesn't have to do with the roblox client.

**Comment by Krcnos** [comment]
resolved
