### ISSUE TITLE
Level 0 Admin

### ISSUE THREAD

**Issue by rev1e** [USAR-Development/Engine-Changelog#51]
**Describe the bug**
I'm an E8 with no admin commands.

**To Reproduce**
I don't know, I finished a phase, went to do a supervision in the same session, tried PMing someone and it didn't work and it said my permission level was demoted to 0.

**Expected behavior**
I expected my PM to go through like normal.

**Screenshots**
![image (10)](https://github.com/USAR-Development/Engine-Changelog/assets/151101648/5f6d7f83-3921-4c42-9a66-40fb1b26d80d)

**Additional context**
Please help, my name is REV1E and I have no admin.

**Comment by Krcnos** [comment]
You are looking at adonis admin commands. Kronos admin is level based and will tell you that you were demoted to "level 0". If you still don't have admin with adonis send a DM to army staff and they'll forward it to me. If they give you a problem just send them a screenshot of this comment.
