### ISSUE TITLE
I am en e2 with bct panel.

### ISSUE THREAD

**Issue by MUSTAFE4343** [USAR-Development/Engine-Changelog#7]
I am able to host bcts and i am not in tradoc i am an normal e2 i want the issue removed asap i dont want to get banned for.

the issue could be because i was drill sergeant 6 hours and got discharged but i noticed i can host bct while in jail. #6 

https://github.com/USAR-Development/Engine-Changelog/assets/146876221/5f09384d-c4e9-45a3-baae-5c3d76117852

**Comment by Krcnos** [comment]
should be fixed
