### ISSUE TITLE
Uniform bug

### ISSUE THREAD

**Issue by alexthegreat727** [USAR-Development/Engine-Changelog#9]
**Describe the bug**
It appears to me and everybody else that he is wearing the wrong uniform, but on his end he is wearing the right uniform

**To Reproduce**
I have no idea

**Expected behavior**
Me and him to see the same thing.

![image](https://github.com/USAR-Development/Engine-Changelog/assets/147208322/4a1f0909-e691-4834-b372-8600873516a7)

![image](https://github.com/USAR-Development/Engine-Changelog/assets/147208322/dfda6635-b46c-45b1-99b6-5870fbb3852f)

**Comment by Krcnos** [comment]
Nothing to go off of here, not reproduceable so not fixable
